import json
import re

def corrigir_codificacao():
    print("=== CORREÇÃO DE CODIFICAÇÃO UTF-8 ===")
    
    # Mapeamento de caracteres deformados para corretos
    correcoes = {
        # Acentos e cedilhas
        'Ã\u0087Ã\u0095ES': 'ÇÕES',
        'Ã\u0087Ã\u0083O': 'ÇÃO',
        'Ã\u0087Ã\u0095': 'ÇÕ',
        'Ã\u0087': 'Ç',
        'Ã\u0095ES': 'ÕES',
        'Ã\u0095': 'Õ',
        'Ã\u0089': 'É',
        'Ã\u0081': 'Á',
        'Ã\u0080': 'À',
        'Ã\u0082': 'Â',
        'Ã\u0083': 'Ã',
        'Ã\u008d': 'Í',
        'Ã\u0093': 'Ó',
        'Ã\u0094': 'Ô',
        'Ã\u009a': 'Ú',
        'Ã\u009c': 'Ü',
        
        # Padrões específicos encontrados
        'REPRESENTAÃ\u0087Ã\u0095ES': 'REPRESENTAÇÕES',
        'REPRESENTAÃ\u0087Ã\u0083O': 'REPRESENTAÇÃO',
        'CONSULTORIA, REPRES E SERVIÃ\u0087OS': 'CONSULTORIA, REPRES E SERVIÇOS',
        'COM. IMP E REPRESENTAÃ\u0087Ã\u0095ES': 'COM. IMP E REPRESENTAÇÕES',
        'SERVIÃ\u0087OS E REPRES': 'SERVIÇOS E REPRES',
        'COMERCIO E REPRESENTAÃ\u0087Ã\u0083O': 'COMERCIO E REPRESENTAÇÃO',
        'COMERCIO E REPRESENTAÃ\u0087Ã\u0095ES': 'COMERCIO E REPRESENTAÇÕES',
        'PRIME REPRESENTAÃ\u0087Ã\u0083O': 'PRIME REPRESENTAÇÃO',
        'REPRESENTAÃ\u0087Ã\u0095ES LTDA': 'REPRESENTAÇÕES LTDA',
        'REPRESENTAÃ\u0087Ã\u0083O S/S': 'REPRESENTAÇÃO S/S',
        'SASSE REPRESENTAÃ\u0087Ã\u0095ES': 'SASSE REPRESENTAÇÕES',
        'V&B REPRESENTAÃ\u0087Ã\u0083O': 'V&B REPRESENTAÇÃO',
        'ZIER REPRESENTAÃ\u0087Ã\u0095ES': 'ZIER REPRESENTAÇÕES',
        
        # Nomes de cidades com problemas
        'SerÃ¡': 'Será',
        'Acrelândia': 'Acrelândia',
        'Alcântara': 'Alcântara',
        'Altamira do Maranhão': 'Altamira do Maranhão',
        'Alto Alegre do Maranhão': 'Alto Alegre do Maranhão',
        'Alto Alegre do Pindaré': 'Alto Alegre do Pindaré',
        'Amapá do Maranhão': 'Amapá do Maranhão',
        'Amarante do Maranhão': 'Amarante do Maranhão',
        'Amparo do São Francisco': 'Amparo do São Francisco',
        'Apicum-Açu': 'Apicum-Açu',
        'Aquidabã': 'Aquidabã',
        'Araguanã': 'Araguanã',
        'Açailândia': 'Açailândia',
        'Açu': 'Açu',
        'Barão de Grajaú': 'Barão de Grajaú',
        'Bela Vista do Maranhão': 'Bela Vista do Maranhão',
        'Belém': 'Belém',
        'Bequimão': 'Bequimão',
        'Brasiléia': 'Brasiléia',
        'Cacaulândia': 'Cacaulândia',
        'Caiçara do Norte': 'Caiçara do Norte',
        'Caiçara do Rio do Vento': 'Caiçara do Rio do Vento',
        'Calçoene': 'Calçoene',
        'Campestre do Maranhão': 'Campestre do Maranhão',
        'Canindé de São Francisco': 'Canindé de São Francisco',
        'Cedro de São João': 'Cedro de São João',
        'Central do Maranhão': 'Central do Maranhão',
        'Centro Novo do Maranhão': 'Centro Novo do Maranhão',
        'Chã Preta': 'Chã Preta',
        'Cidelândia': 'Cidelândia',
        'Coité do Nóia': 'Coité do Nóia',
        'Conceição do Lago-Açu': 'Conceição do Lago-Açu',
        'Coronel João Pessoa': 'Coronel João Pessoa',
        'Cândido Mendes': 'Cândido Mendes',
        'Epitaciolândia': 'Epitaciolândia',
        'Espigão d\'Oeste': 'Espigão d\'Oeste',
        'Estância': 'Estância',
        'Feira Nova do Maranhão': 'Feira Nova do Maranhão',
        'Fernando Falcão': 'Fernando Falcão',
        'Florânia': 'Florânia',
        'Gonçalves Dias': 'Gonçalves Dias',
        'Governador Edison Lobão': 'Governador Edison Lobão',
        'Graça Aranha': 'Graça Aranha',
        'Guamaré': 'Guamaré',
        'Guimarães': 'Guimarães',
        'Igarapé Grande': 'Igarapé Grande',
        'Igarapé do Meio': 'Igarapé do Meio',
        'Ipanguaçu': 'Ipanguaçu',
        'Itapuã do Oeste': 'Itapuã do Oeste',
        'Itinga do Maranhão': 'Itinga do Maranhão',
        'Jacaré dos Homens': 'Jacaré dos Homens',
        'Japoatã': 'Japoatã',
        'Jaçanã': 'Jaçanã',
        'Jordão': 'Jordão',
        'Joselândia': 'Joselândia',
        'José da Penha': 'José da Penha',
        'João Câmara': 'João Câmara',
        'João Dias': 'João Dias',
        'João Lisboa': 'João Lisboa',
        'Junco do Maranhão': 'Junco do Maranhão',
        'Lagoa Grande do Maranhão': 'Lagoa Grande do Maranhão',
        'Lucrécia': 'Lucrécia',
        'Magalhães de Almeida': 'Magalhães de Almeida',
        'Maracaçumé': 'Maracaçumé',
        'Maranhãozinho': 'Maranhãozinho',
        'Matões': 'Matões',
        'Matões do Norte': 'Matões do Norte',
        'Mazagão': 'Mazagão',
        'Milagres do Maranhão': 'Milagres do Maranhão',
        'Minador do Negrão': 'Minador do Negrão',
        'Monção': 'Monção',
        'Mâncio Lima': 'Mâncio Lima',
        'Nova Brasilândia d\'Oeste': 'Nova Brasilândia d\'Oeste',
        'Nova Mamoré': 'Nova Mamoré',
        'Nova Olinda do Maranhão': 'Nova Olinda do Maranhão',
        'Nova União': 'Nova União',
        'Olho d\'Água das Cunhãs': 'Olho d\'Água das Cunhãs',
        'Olinda Nova do Maranhão': 'Olinda Nova do Maranhão',
        'Olivença': 'Olivença',
        'Palmeirândia': 'Palmeirândia',
        'Paço do Lumiar': 'Paço do Lumiar',
        'Piaçabuçu': 'Piaçabuçu',
        'Pilões': 'Pilões',
        'Pindaré-Mirim': 'Pindaré-Mirim',
        'Pinhão': 'Pinhão',
        'Porto Real do Colégio': 'Porto Real do Colégio',
        'Porto Rico do Maranhão': 'Porto Rico do Maranhão',
        'Poço Branco': 'Poço Branco',
        'Poço Redondo': 'Poço Redondo',
        'Poço Verde': 'Poço Verde',
        'Poço das Trincheiras': 'Poço das Trincheiras',
        'Poção de Pedras': 'Poção de Pedras',
        'Presidente Médici': 'Presidente Médici',
        'Pão de Açúcar': 'Pão de Açúcar',
        'Riachão': 'Riachão',
        'Riachão do Dantas': 'Riachão do Dantas',
        'Santa Filomena do Maranhão': 'Santa Filomena do Maranhão',
        'Santa Quitéria do Maranhão': 'Santa Quitéria do Maranhão',
        'Santana do Maranhão': 'Santana do Maranhão',
        'Santana do São Francisco': 'Santana do São Francisco',
        'Santo Amaro do Maranhão': 'Santo Amaro do Maranhão',
        'Serra de São Bento': 'Serra de São Bento',
        'Serrano do Maranhão': 'Serrano do Maranhão',
        'Simão Dias': 'Simão Dias',
        'Sucupira do Riachão': 'Sucupira do Riachão',
        'São Benedito do Rio Preto': 'São Benedito do Rio Preto',
        'São Bento': 'São Bento',
        'São Bento do Norte': 'São Bento do Norte',
        'São Bento do Trairí': 'São Bento do Trairí',
        'São Bernardo': 'São Bernardo',
        'São Brás': 'São Brás',
        'São Cristóvão': 'São Cristóvão',
        'São Domingos': 'São Domingos',
        'São Domingos do Azeitão': 'São Domingos do Azeitão',
        'São Domingos do Maranhão': 'São Domingos do Maranhão',
        'São Felipe d\'Oeste': 'São Felipe d\'Oeste',
        'São Fernando': 'São Fernando',
        'São Francisco': 'São Francisco',
        'São Francisco do Brejão': 'São Francisco do Brejão',
        'São Francisco do Guaporé': 'São Francisco do Guaporé',
        'São Francisco do Maranhão': 'São Francisco do Maranhão',
        'São Francisco do Oeste': 'São Francisco do Oeste',
        'São Félix de Balsas': 'São Félix de Balsas',
        'São Gonçalo do Amarante': 'São Gonçalo do Amarante',
        'São José da Laje': 'São José da Laje',
        'São José da Tapera': 'São José da Tapera',
        'São José de Mipibu': 'São José de Mipibu',
        'São José de Ribamar': 'São José de Ribamar',
        'São José do Campestre': 'São José do Campestre',
        'São José do Seridó': 'São José do Seridó',
        'São José dos Basílios': 'São José dos Basílios',
        'São João Batista': 'São João Batista',
        'São João da Baliza': 'São João da Baliza',
        'São João do Carú': 'São João do Carú',
        'São João do Paraíso': 'São João do Paraíso',
        'São João do Sabugi': 'São João do Sabugi',
        'São João do Soter': 'São João do Soter',
        'São João dos Patos': 'São João dos Patos',
        'São Luiz': 'São Luiz',
        'São Luís': 'São Luís',
        'São Luís Gonzaga do Maranhão': 'São Luís Gonzaga do Maranhão',
        'São Luís do Quitunde': 'São Luís do Quitunde',
        'São Mateus do Maranhão': 'São Mateus do Maranhão',
        'São Miguel': 'São Miguel',
        'São Miguel do Aleixo': 'São Miguel do Aleixo',
        'São Miguel do Gostoso': 'São Miguel do Gostoso',
        'São Miguel do Guaporé': 'São Miguel do Guaporé',
        'São Miguel dos Campos': 'São Miguel dos Campos',
        'São Miguel dos Milagres': 'São Miguel dos Milagres',
        'São Paulo do Potengi': 'São Paulo do Potengi',
        'São Pedro': 'São Pedro',
        'São Pedro da Água Branca': 'São Pedro da Água Branca',
        'São Pedro dos Crentes': 'São Pedro dos Crentes',
        'São Rafael': 'São Rafael',
        'São Raimundo das Mangabeiras': 'São Raimundo das Mangabeiras',
        'São Raimundo do Doca Bezerra': 'São Raimundo do Doca Bezerra',
        'São Roberto': 'São Roberto',
        'São Sebastião': 'São Sebastião',
        'São Tomé': 'São Tomé',
        'São Vicente': 'São Vicente',
        'São Vicente Ferrer': 'São Vicente Ferrer',
        'Tufilândia': 'Tufilândia',
        'Turiaçu': 'Turiaçu',
        'Turilândia': 'Turilândia',
        'Uiramutã': 'Uiramutã',
        'União dos Palmares': 'União dos Palmares',
        'Viçosa': 'Viçosa',
        'Zé Doca': 'Zé Doca',
        'Água Doce do Maranhão': 'Água Doce do Maranhão',
        
        # Outros caracteres comuns
        'André': 'André',
        'MEDICILÂNDIA': 'MEDICILÂNDIA',
        
        # Padrões gerais de correção
        'Ã¡': 'á',
        'Ã¢': 'â',
        'Ã£': 'ã',
        'Ã¤': 'ä',
        'Ã¥': 'å',
        'Ã§': 'ç',
        'Ã¨': 'è',
        'Ã©': 'é',
        'Ãª': 'ê',
        'Ã«': 'ë',
        'Ã¬': 'ì',
        'Ã­': 'í',
        'Ã®': 'î',
        'Ã¯': 'ï',
        'Ã±': 'ñ',
        'Ã²': 'ò',
        'Ã³': 'ó',
        'Ã´': 'ô',
        'Ãµ': 'õ',
        'Ã¶': 'ö',
        'Ã¹': 'ù',
        'Ãº': 'ú',
        'Ã»': 'û',
        'Ã¼': 'ü',
        'Ã½': 'ý',
        'Ã¿': 'ÿ',
        'Ã€': 'À',
        'Ã': 'Á',
        'Ã‚': 'Â',
        'Ãƒ': 'Ã',
        'Ã„': 'Ä',
        'Ã…': 'Å',
        'Ã‡': 'Ç',
        'Ãˆ': 'È',
        'Ã‰': 'É',
        'ÃŠ': 'Ê',
        'Ã‹': 'Ë',
        'ÃŒ': 'Ì',
        'Ã': 'Í',
        'ÃŽ': 'Î',
        'Ã': 'Ï',
        'Ã\u0091': 'Ñ',
        'Ã\u0092': 'Ò',
        'Ã"': 'Ó',
        'Ã"': 'Ô',
        'Ã•': 'Õ',
        'Ã–': 'Ö',
        'Ã™': 'Ù',
        'Ãš': 'Ú',
        'Ã›': 'Û',
        'Ãœ': 'Ü',
        'Ã': 'Ý',
        'ÃŸ': 'ß'
    }
    
    try:
        # Ler arquivo atual
        with open('old/representantes.json', 'r', encoding='utf-8') as f:
            content = f.read()
        
        print(f"Arquivo original: {len(content)} caracteres")
        
        # Aplicar correções
        content_corrigido = content
        correcoes_aplicadas = 0
        
        for errado, correto in correcoes.items():
            if errado in content_corrigido:
                count = content_corrigido.count(errado)
                content_corrigido = content_corrigido.replace(errado, correto)
                correcoes_aplicadas += count
                print(f"✓ Corrigido '{errado}' -> '{correto}' ({count} ocorrências)")
        
        # Verificar se é JSON válido
        try:
            data = json.loads(content_corrigido)
            print("✓ JSON válido após correções")
        except json.JSONDecodeError as e:
            print(f"❌ Erro de JSON após correções: {e}")
            return
        
        # Salvar arquivo corrigido
        with open('old/representantes.json', 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        
        print(f"\n✅ CORREÇÃO CONCLUÍDA!")
        print(f"✓ Total de correções aplicadas: {correcoes_aplicadas}")
        print(f"✓ Arquivo salvo com codificação UTF-8 correta")
        print(f"✓ Caracteres especiais agora estão corretos")
        
    except Exception as e:
        print(f"❌ Erro ao corrigir codificação: {e}")

if __name__ == "__main__":
    corrigir_codificacao()